version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - security
    ignore:
      - dependency-name: next
        update-types: [version-update:semver-major]
      - dependency-name: eslint-config-next
        update-types: [version-update:semver-major]
      - dependency-name: eslint
        update-types: [version-update:semver-major]
      - dependency-name: tailwindcss
        update-types: [version-update:semver-major]
      - dependency-name: typescript
        update-types: [version-update:semver-major]
      - dependency-name: "@types/node"
        update-types: [version-update:semver-major]
    groups:
      web-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "11:00"
      timezone: Asia/Tokyo
    labels:
      - dependencies
      - ci
